### ISSUE TITLE
[BUG] Server thinks player still has hat on death

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#1]
**I have checked...**
- [x] ...if there are any similar bug reports
- [x] ...if a bug fix is already planned

**Complete description**
When you have a HAT cosmetic applied (this does not apply to backpacks), and then you die, when you go back into the GUI it will send "cosmetic removed" in chat, even though the player doesn't actually have the cosmetic applied anymore.

See this video for a better explanation:
https://user-images.githubusercontent.com/60053521/145489148-aaf531b8-f2a2-4e77-88e8-49648874c5ff.mp4

**Possible solution**
Not sure

**Error/Server log**
n/a

**Comment by RangeBanenge** [comment]
Can you show how you made the transition between other menus?
