### ISSUE TITLE
cosmetics token

### ISSUE THREAD

**Issue by magicelk235** [HibiscusMC/HMCCosmetics#102]
### Feature Description

the same as it was in the past
https://docs.hibiscusmc.com/hmccosmetics%20legacy/Tokens

### Implementation Description

the same as it was in the past
https://docs.hibiscusmc.com/hmccosmetics%20legacy/Tokens

**Comment by LoJoSho** [comment]
This is not planned. You can do a similar thing with a voucher plugin.
