### ISSUE TITLE
[SUGGESTION] possibility to add Cosmetics to NPCS

### ISSUE THREAD

**Issue by itsMarkiS** [HibiscusMC/HMCCosmetics#106]
### Feature Description

maybe with citizen or something like this

would be great if you could use like

/cosmetic npc add <npc-id> <cosmetic>
/cosmetic npc remove <npc-id> <cosmetic>

**Comment by LoJoSho** [comment]
There are no plans to add such support for Citizens in the main plugin. There was talk about spinning it off as an add-on, but that never came to fruition to my knowledge.
