### ISSUE TITLE
Multiple Wardrobe Rooms

### ISSUE THREAD

**Issue by BendersRepublic** [HibiscusMC/HMCCosmetics#108]
### Feature Description

Ability to setup multiple rooms. On my server we have 5 different wardrobe room designs. Players can access it by stepping through its specific door, was hoping we can keep this feature while we make our switch to hmc

### Implementation Description

uhh I would hope and think it's simple, like defining the wardrobe name after typing the location

**Comment by LoJoSho** [comment]
This was something that was talked about a bit in #54, it isn't a feature I am completely opposed to, but this is already possible through third party plugins (although it would be nice having it all built in!)
