### ISSUE TITLE
attached items cloning

### ISSUE THREAD

**Issue by BendersRepublic** [HibiscusMC/HMCCosmetics#109]
### Feature Description

So the attached locked and equipped items need to be singlehandedly defined, even after defining the above parent item. I'm hoping for some sort of option that will allow my cosmetics to directly pull the model data and whatever else directly to the child items.

**Comment by LoJoSho** [comment]
This is something that everything has a different need for what their items should do. I think I will add a setting to modify this, but this is a low-priority issue for me.
