### ISSUE TITLE
[BUG] Cannot create new pages

### ISSUE THREAD

**Issue by LuluxClient** [HibiscusMC/HMCCosmetics#11]
**I have checked...**
- [ ] ...if there are any similar bug reports
- [ ] ...if a bug fix is already planned
- I checked github and the wiki

**Complete description**
I created a new .yml file called menu-2.yml and copy pasted the content of the main.yml file.
After restarting it doesn't load my 2nd menu page and in console I'm getting this error when reloading and I can see only 1 gui is being loaded

**Possible solution**
If you have any possible solutions, write them here, if not, leave it blank or put "N/A".
none

**Error/Server log**
[If you have any errors put them in here (from paste.gg or sentry)](https://pastebin.com/zLqUe7Uz)

**Comment by LuluxClient** [comment]
Forgot to add that if I edit the perm it fixes the issue but it's weird I cannot put the same perm ;(

**Comment by LuluxClient** [comment]
Update: If you reload again it will say you're using the same permission when it's not,
To reproduce it you just need to create a 2nd page and do /cosmetics reload twice. Even if you have different perms after reloading it will break.

**Comment by Fisher2911** [comment]
I know how to fix this, I'm not sure why I thought people would only have one permission per cosmetic lol.

**Comment by lucian929** [comment]
Fixed (update 1.8.1)
