### ISSUE TITLE
[SUGGESTION] Small Features for equipped cosmetics

### ISSUE THREAD

**Issue by itsMarkiS** [HibiscusMC/HMCCosmetics#113]
### Feature Description

For example, Equipped cosmetics, instead of displaying a custom item, could simply have a different name, lore, or even be enchanted

**Comment by LoJoSho** [comment]
Is this for menus? If so, this has already been done, if you don't define a material a second time in equipped item.

If this is for equipped cosmetics in your inventory, I don't see myself adding it. It doesn't seem like a feature that is needed and the spirit of the plugin is wearing cosmetics, not modifying already existing armor.

**Comment by itsMarkiS** [comment]
> Is this for menus? If so, this has already been done, if you don't define a material a second time in equipped item.
> 
> If this is for equipped cosmetics in your inventory, I don't see myself adding it. It doesn't seem like a feature that is needed and the spirit of the plugin is wearing cosmetics, not modifying already existing armor.

its for the menus, like, if you equip the cosmetic it would get a enchanted glint instead of modyfing what item it is (in the docs, for example, it is a wool block) in my suggestion it is like, it will still be the same item, but with a enchanted glint

**Comment by LoJoSho** [comment]
That doesn't seem at all in the spirit of HMCC, that sounds like an entirely different plugin idea.
