### ISSUE TITLE
 problem with plugin commands

### ISSUE THREAD

**Issue by JeuneUrus** [HibiscusMC/HMCCosmetics#115]
### Plugin Version

2.4.6

### Server Version

Spigot 1.19.4

### Issue description

Hi, I installed the plugin with itemsadder according to the instructions of "README.txt" in the HMCCosmeticsRemapped-2.4.6.zip file, the texture pack works very well, the objects are present in the menu of itemsadder but compared to the Hmccosmetic plugin itself, I can't open the menu to access cosmetics. When I use /cosmetics it says "invalid player!" and sometimes it just says an internal error occured.

### Steps to reproduce

1 - I start my serv
2 - i use /cosmetic
3 - it says an internal error occured
(I did not touch anything in the configuration files and in the plugin files)

### Issue priority

High (immediate attention needed)

### Other Versions

hmc comsmetic 2.4.6
itemsadder 3.5.0

**Comment by LoJoSho** [comment]
I assume you manage to figure out how to fix the error on your own. If you need further assistance, the best way to get in touch with us is on our [discord server](https://discord.gg/pcm8kWrdNt).
