### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by JeuneUrus** [HibiscusMC/HMCCosmetics#116]
### Plugin Version

2.4.6

### Server Version

Spigot 1.19.4

### Issue description

The resource pack does not load in the cosmetic gui only but when I give myself a cosmetic object from the hmcosmetic plugin thanks to itemadder, the texture works

### Steps to reproduce

when I use /cosmetic it does this
![image](https://github.com/HibiscusMC/HMCCosmetics/assets/136896572/cb94fd8a-d07d-43f1-b000-18d9262f9d16)
when I use /iagive JeuneUrus hmccosmetics:garbage_truck_balloon (for example but it works with all default cosmetics)
it does this
![image](https://github.com/HibiscusMC/HMCCosmetics/assets/136896572/184e9ec0-b79d-4ccc-88ba-76106a9365dd)
(I did not touch any file in the configuration and in the hmccosmetics plugin files)

### Issue priority

High (immediate attention needed)

### Other Versions

itemadder - 3.5.0

**Comment by LoJoSho** [comment]
Do not make frivolous high-priority bug reports, this is a configuration error caused by not putting the `ItemsAdder Configuration/HMCCosmetics` into the HMCCosmetics folder.
