### ISSUE TITLE
the default cosmetics do not appear

### ISSUE THREAD

**Issue by JeuneUrus** [HibiscusMC/HMCCosmetics#117]
### Plugin Version

2.4.6

### Server Version

Spigot 1.19.4

### Issue description

Default cosmetics don't appear in the default menu, seulement ça apparait
![image](https://github.com/HibiscusMC/HMCCosmetics/assets/136896572/1022bc35-5012-4174-ba5c-8c8f498e0b3e)

### Steps to reproduce

I did not touch the config file nor the plugin file

### Issue priority

Low (slightly annoying)

### Other Versions

Itemadder 3.5.0

**Comment by LoJoSho** [comment]
This is a configuration error, not a bug with HMCC. Go to our discord server for help.
