### ISSUE TITLE
Cant use modelengine models with Uppercase letters

### ISSUE THREAD

**Issue by Sylvamy** [HibiscusMC/HMCCosmetics#118]
### Plugin Version

2.4.10

### Server Version

Paper-69-1.20.1

### Issue description

When using ModelEngine for balloons if the model name has uppercase characters the plugin is unable to find the model, example:
Balloon_Bee - Doesn't load in HMCCosmetics
Rename file to balloon_bee - Loads in HMCCosmetics

Other plugins allow uppercase characters so must be a HMCCosmetics issue (mm for example)

### Steps to reproduce

Use Uppercase file names

### Issue priority

Low (slightly annoying)

### Other Versions

ModelEngine 3.1.8

**Comment by LoJoSho** [comment]
I am unsure how this could be occurring. HMCC simply takes the id in the config and then goes to ME with the same id to get it. Never the less, I shall look into it.

**Comment by LoJoSho** [comment]
It appears ME does not support capitalization in their models. This is something that would be a relatively easy fix (just make the id lowercase before handing it to Model Engine), but with Model Engine 4 coming out in the future, I am unsure if they will add capitalization, which would break previous servers who relied on it all being lowercase.

**Comment by Sylvamy** [comment]
> It appears ME does not support capitalization in their models. This is something that would be a relatively easy fix (just make the id lowercase before handing it to Model Engine), but with Model Engine 4 coming out in the future, I am unsure if they will add capitalization, which would break previous servers who relied on it all being lowercase.

Are you sure about that? All my other models have capitalization and work just fine for mythic and stuff

**Comment by LoJoSho** [comment]
Other plugins most likely just set their strings to lowercase before sending it to ModelEngine
