### ISSUE TITLE
[FEATURE] update github code to 1.9.0

### ISSUE THREAD

**Issue by QuintenQVD0** [HibiscusMC/HMCCosmetics#12]
**I have checked...**

- [x] ...if there are any similar features in other branches
- [x] ...if there are any similar issues
- [x] ...if such a feature is already planned

**Complete description**
Can you update the master branch on github to v 1.9.0?

**Reason for feature request**
I don't have any money but I can build java plugins and I like to use the newest update

**Comment by Skyslycer** [comment]
Why? The code is on the dev branch, just build from that.
