### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by RangeBanenge** [HibiscusMC/HMCCosmetics#130]
### Plugin Version

2.6.5

### Server Version

paper 1.20

### Issue description

I can’t make an item on another page; there’s nothing in the console and nothing happens in the menu either.

### Steps to reproduce

  hat2:
    slots:
      - 44
    material: PAPER
    name: "<#F7DCFA>Next Page"
    amount: 1
    model-data: 1
    action:
      any:
        open-menu: hat2

### Issue priority

Low (slightly annoying)

**Comment by LoJoSho** [comment]
You are using an action that does not exist. If you need configuration help, feel free to join the support [Discord](https://discord.gg/pcm8kWrdNt) where we can help you further.

**Comment by RangeBanenge** [comment]
Please show me how to do this in the menu config


пт, 29 дек. 2023 г. в 21:18, LoJoSho ***@***.***>:
