### ISSUE TITLE
Incorrect title in dye menu and HMCColor slot sync issues

### ISSUE THREAD

**Issue by BimboBigBoy** [HibiscusMC/HMCCosmetics#137]
### Plugin Version

2.7.3-DEV (de1e5b)

### Server Version

paper-196-1.20.1

### Issue description

I report two problems
1. The title of the dyeing menu is not the same as the one set in HMCColor.
2. When I change the input/output slot of HMCColor it does not show the changes made to the slot in the HMCCosmetics dyeing menu and I cannot finish dyeing a cosmetic because the dyed cosmetic is not shown in the output.

### Steps to reproduce

# Problem 1:
Change the title in HMCColor or simply note that it is not the same title used in HMCColor.

![image](https://github.com/HibiscusMC/HMCCosmetics/assets/170268499/e2c3f609-0b39-42e4-aafb-0aab30dbd026)
_Picture 1. HMCCosmetics dye menu, the title assigned in hmccolor is not displayed correctly._

![image](https://github.com/HibiscusMC/HMCCosmetics/assets/170268499/a9dbd05d-a125-455b-b99a-7a14320052fa)
_Picture 2. HMCColor gui correctly displays the assigned title_

# Problem 2:
1. Change the input/output slots of HMCColor 
2. Try to dye a cosmetic and notice that the slots have been changed and you can't even finish dyeing a cosmetic.

![image](https://github.com/HibiscusMC/HMCCosmetics/assets/170268499/d87bab87-7ee4-4316-bb30-e50c903eb802)
_Picture 3. HMCCosmetics dye menu after changing input/output slots_

### Issue priority

Medium (should be fixed somewhat soon)

### Other Versions

- HibiscusCommons 0.3.3
- HMCColor latest update github: (fix: input slot not denying non colorable items)

**Comment by LoJoSho** [comment]
This is a configuration issue, not a plugin issue. Use the discord for support like this.
