### ISSUE TITLE
Helmet doesn't lose durability.

### ISSUE THREAD

**Issue by meowisme** [HibiscusMC/HMCCosmetics#138]
### Plugin Version

2.7.2 (?)

### Server Version

Spigot 1.20-1.20.5

### Issue description

I play on a server that uses HMCCosmetics but I'm not aware entirely of the plugin version although I assume it's up to date.
I've noticed that my helmet never loses durability. After some friendly pvp, I'd check my helm and it's still full.
Is this intentional ?

### Steps to reproduce

Wear cosmetic over helmet.
Take damage that would normally hurt the helmet.

### Issue priority

Low (slightly annoying)

**Comment by LoJoSho** [comment]
This is very clearly not the case with base HMCC. Closing as I can't replicate it. Please do not open an issue if you don't have access to the backend of a server running HMCC.
