### ISSUE TITLE
Issues with MySQL wait_timeout

### ISSUE THREAD

**Issue by NekrosBurek** [HibiscusMC/HMCCosmetics#140]
### Plugin Version

2.7.2-DEV

### Server Version

git-Paper-496 (MC: 1.20.4)

### Issue description

Issue i am facing is that server after hours of "idle" time with or without players causes this issue i could increase the wait_timeout but would be probably recommended use of either HikariCP or autoReconnect=true

There is a log i got if needed i can provide whole latest log in the comment
https://paste.nekroplex.com/davevobica.md

### Steps to reproduce

1. Start server and use MySQL connection
2. Leave the server connected and plugin connected to database for at least 8 hours

### Issue priority

Medium (should be fixed somewhat soon)

**Comment by LoJoSho** [comment]
Hikari seems a bit overkill for what we are doing, I do have auto reconnect set to true, https://github.com/HibiscusMC/HMCCosmetics/blob/remapped/common/src/main/java/com/hibiscusmc/hmccosmetics/database/types/MySQLData.java#L119, but I may have to add some logic around it to capture if the connection is closed before I try to do anything with the database.
