### ISSUE TITLE
Add a give command (w/ LuckPerms hook)

### ISSUE THREAD

**Issue by NoltoxGit** [HibiscusMC/HMCCosmetics#142]
### Feature Description

Hello,
Would it be possible to add a command to give a cosmetic to a player (`/cosmetic give <ID> <USERNAME>`) and also make it so that when you give the cosmetic to a player, it gives permission directly to the player (from the [LuckPerms API](https://luckperms.net/wiki/Developer-API-Usage)).

This could be really really cool! :)

**Comment by LoJoSho** [comment]
This seems unnecessary, as you can just use the Luckperms command to give the player permission for said cosmetic.
