### ISSUE TITLE
[BUG] teleport to another world with activated ballon.

### ISSUE THREAD

**Issue by Moises-pe** [HibiscusMC/HMCCosmetics#18]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When teleporting to another world with a balloon activated, the balloon disappears and an error is generated on the console. While in the cosmetics menu, the balloon is still activated.

### Steps to reproduce

Equip a balloon and tp to another world.

### Plugin Version

1.10.3

### ModelEngine Version

R2.4.2

### Server Version

Paper 1.18.1

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by lucian929** [comment]
Fixed in 1.11.0-BETA-2
