### ISSUE TITLE
[BUG] Plugin incompatability - McRPG

### ISSUE THREAD

**Issue by Verdux** [HibiscusMC/HMCCosmetics#21]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

There is currently an incompatibility with the plugin McRPG [(Link)](https://www.spigotmc.org/resources/mcrpg.63020/). Whenever this plugin tracks actions such as breaking blocks, damaging mobs etc... it breaks the cosmetics display from HMCCosmetics. I have spoken to the dev of this plugin and he says the issue is likely on your end.

See the following gif for an example: https://i.gyazo.com/da3544cce1c8d7bb19c348b43935586f.gif

McRPG may be premium but it is open source, the code can be found here: [GitHub](https://github.com/Eunoians/McRPG)

I do have a still open ticket on the discord with the walk through of this issue if you need a refresher, please see [Discord](https://discord.com/channels/930592346201026590/948580818308173824)

### Steps to reproduce

Install both HMCCosmetics and McRPG
Apply cosmetics
Break a block

### Plugin Version

v1.11.0-BETA-3

### ModelEngine Version

R2.5.1

### Server Version

Paper 1.18.1 #216

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by retrooper** [comment]
Might be late but update ModelEngine, they recently put out a fix on their end for this.

**Comment by LoJoSho** [comment]
Marking this as Limbo, when HMCC Remapped releases, please try this again and see if the issue persists.

**Comment by LoJoSho** [comment]
I am closing this ticket as it has been dormant for over 6 months now and an entire recode has happened in that time. If this issue persists, feel free to open a new ticket!
