### ISSUE TITLE
Balloons Issue

### ISSUE THREAD

**Issue by GrayHay** [HibiscusMC/HMCCosmetics#22]
When you type /cosmetics npc apply {npc number} BALLOON {cosmetic} it will attach the balloon to the hand. when you /npc remove, the balloon stays there for all players until they rejoin.

**Comment by LoJoSho** [comment]
This has been marked as Limbo, Remapped may or may not support Citizens/NPCs, what's more, likely is that it will be split into a different plugin in the future.

**Comment by LoJoSho** [comment]
This has not been readded to HMCCosmetics.
