### ISSUE TITLE
[FEATURE] Command to set locations

### ISSUE THREAD

**Issue by GrayHay** [HibiscusMC/HMCCosmetics#24]
### I have checked that...

- [x] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

add an admin command that will take the players location and set it to that specified location in config

ie: /cosmetics setwardrobe wardrobe-location
ie: /cosmetics setwardrobe viewer-location
ie: /cosmetics setwardrobe leave-location

### Config Changes

#n/a

**Comment by LoJoSho** [comment]
On my radar for HMCC Remapped, but very low priority as you only really need to do it once in the config.

**Comment by LoJoSho** [comment]
Implemented in Remapped versions,
https://docs.hibiscusmc.com/hmccosmetics%20remapped/Commands
