### ISSUE TITLE
[FEATURE] Expanded PAPI Placeholders

### ISSUE THREAD

**Issue by Sqbri** [HibiscusMC/HMCCosmetics#27]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Either a full player profile plugin dedicated to HMCCosmetics like this one made for MagicCosmetics https://www.spigotmc.org/resources/playerprofile-for-magic-cosmetic.103067/

or

New placeholders such as: %HMCCOSMETICS_HAT_MATERIAL%, %HMCCOSMETICS_HAT_NAME%, %HMCCOSMETICS_HAT_LORE%, etc. so there doesn't have to be a new plugin made

Types:
HAT, BACKPACK, OFFHAND, HELMET, CHESTPLATE, LEGGINGS, BOOTS
List of Placeholders:
%HMCCOSMETICS_< TYPE >_MATERIAL%
%HMCCOSMETICS_< TYPE >_CUSTOMMODELDATA%
%HMCCOSMETICS_< TYPE >_NAME%
%HMCCOSMETICS_< TYPE >_LORE%

**Comment by LoJoSho** [comment]
PAPI support is a low priority for me right now, however, this is on my radar.

**Comment by LoJoSho** [comment]
Implemented in the Remapped versions, https://docs.hibiscusmc.com/hmccosmetics%20remapped/PlaceholderAPI
