### ISSUE TITLE
[FEATURE] Store Cosmetic Hidden in Database

### ISSUE THREAD

**Issue by YrChen1001** [HibiscusMC/HMCCosmetics#30]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

let command `/cosmetics hide` can be record
like when server restart or player rejoin don't need setup again.

**Comment by LoJoSho** [comment]
Marking this as limbo, as this feature currently isn't in HMCC Remapped and may be added. Will keep this issue in the loop.

**Comment by LoJoSho** [comment]
This has been added; https://github.com/HibiscusMC/HMCCosmetics/commit/aecd40ba5aacf7374d0459abcc6f16a713c7d0dd
