### ISSUE TITLE
Texture not loading all resources

### ISSUE THREAD

**Issue by sujyrokimora** [HibiscusMC/HMCCosmetics#32]
Hi im using itemsadder and the textures didnt all compile well. 
How to fix this???
![image](https://user-images.githubusercontent.com/37046592/185719329-56808a89-5f12-4a92-a0eb-2deb4736f495.png)
https://www.dropbox.com/s/7hzlo68x8uqdx8i/pack_beta2.zip?dl=1

**Comment by lucian929** [comment]
Hi there! Please join our [Discord](https://discord.gg/pcm8kWrdNt) to get plugin support 🙂
