### ISSUE TITLE
[BUG] Wardrobe NPCs are visible on tablist

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#34]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

https://discord.com/channels/930592346201026590/930614642013773824/1020962658742186017

### Steps to reproduce

https://discord.com/channels/930592346201026590/930614642013773824/1020962658742186017

### Plugin Version

beta-5

### ModelEngine Version

n/a

### Server Version

1.19.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by LoJoSho** [comment]
I have looked into this a bit more and it appears I need to deal with team packets or something of the like in order to get this to work. On my radar, but a low priority for now.

**Comment by LoJoSho** [comment]
Should now be fixed with [#c3a085585bdf21e88fbf8dc01c6703cb8b3c90ef](https://github.com/HibiscusMC/HMCCosmetics/commit/c3a085585bdf21e88fbf8dc01c6703cb8b3c90ef)
