### ISSUE TITLE
[FEATURE] Particles Action

### ISSUE THREAD

**Issue by ghost** [HibiscusMC/HMCCosmetics#35]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Would be nice to have a customizable particles/sound effects (maybe even our own from a resource pack) for when cosmetics are applied. Here's an example:

https://user-images.githubusercontent.com/118545275/204636350-a7be6fac-71de-4431-a3e4-a9d944ce5e3d.mp4

(Particle effects list I found was from the Magic Plugin by NathanWolf, here: https://reference.elmakers.com/#effects.particle)

(Here's the list of how the **style** of particles and how they would appear in game: https://reference.elmakers.com/#effectlib)

### Config Changes

ACTIONS:
        # Particles (chosen either from a preset list)
![image](https://user-images.githubusercontent.com/118545275/204635799-e99bfb7c-0216-482f-ab62-58017a3cff6d.png)

        particles: <PARTICLE_PRESET>
        particle_style: <PARTICLE_STYLE> #chosen from effectlib portion

**Comment by LoJoSho** [comment]
It seems like it's doable, especially with the new action system.

**Comment by LoJoSho** [comment]
This has been added in 2.1.0
