### ISSUE TITLE
[FEATURE] Re-implement first person cosmetics

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#38]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

It would be great if the first-person cosmetic feature was added back in Remapped.

I think that this would be quite simple to do now that cosmetics are split into their own file, so only a new cosmetic type (something like `FIRST_PERSON_BACKPACK` could be added).

**Comment by LoJoSho** [comment]
This is something I would also like to reimplement, however, @Fisher2911 would most likely need to help me a bit as I am confused about how we managed to do what he did, even after looking at the code.

**Comment by LoJoSho** [comment]
Implemented in 2.5.0
