### ISSUE TITLE
[FEATURE] Update polymart page

### ISSUE THREAD

**Issue by SubGplayz** [HibiscusMC/HMCCosmetics#39]
### I have checked that...

- [x] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

When coming back to HMCCosmetics, I noticed one thing that isn't very good; none of the new features have been added to the plugin description on polymart. This isn't good because it may lead potential customers to believe that the plugin doesn't have some of the recently added features, leading them to find a different plugin.

**Comment by LoJoSho** [comment]
This is something that has been getting talked about in the development discord of HMCC. It's something that needs to be done.
