### ISSUE TITLE
[FEATURE] MC Pets integration

### ISSUE THREAD

**Issue by SubGplayz** [HibiscusMC/HMCCosmetics#40]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I think it would be amazing if there was some sort of [MC Pets](https://mythiccraft.io/index.php?resources/mccosmetics-the-ultimate-cosmetics-plugin.818/) integration, or integration with a plugin that does something similar, so that they can be accessed and equipped in the same gui as the cosmetics.

### Config Changes

I'm not really sure about this, so ill let somebody more qualified decide, if its ever added ;)

**Comment by LoJoSho** [comment]
Definitely, something that would improve HMCC if there could be integration with MC Pets. I am unable to work on this feature right now, however, if another developer wishes to open a PR request, I'm more than willing to look into merging it.

**Comment by LoJoSho** [comment]
You can do this via commands using the GUI system built into the plugin, for example using an empty GUI item type then attaching commands to the item. You can read about the GUI system here, https://docs.hibiscusmc.com/hmccosmetics%20remapped/GUI-Configuration
