### ISSUE TITLE
[FEATURE] Hide cosmetics in 1st person

### ISSUE THREAD

**Issue by SubGplayz** [HibiscusMC/HMCCosmetics#41]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Pretty sure this existed in before everything was remapped, if not then oh well, but there is a feature that some cosmetics plugins have where they hide cosmetics such as backpacks in first person so you don't see it

**Comment by lucian929** [comment]
This issue already exists as #38, closing.
