### ISSUE TITLE
[FEATURE] Toggle for wardrobe npc to always be there

### ISSUE THREAD

**Issue by SubGplayz** [HibiscusMC/HMCCosmetics#42]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I think it would be cool for a preview of what cosmetics you have equipped to always be visible in an area, and it would also make it easier for new players to find out about the wardrobe on servers.

**Comment by LoJoSho** [comment]
This would require some serious rewrite to our current system, as it's not at all designed to be used in this way. Will be put on the back burner.
