### ISSUE TITLE
[FEATURE] Sound action 

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#43]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I think it would be great if a sound action was added to Remapped. This could be used to improve the customizability of UI's.
Ideally, this would support custom sounds (sounds within custom namespaces, or even just custom sounds within the Minecraft namespace). 

### Config Changes

    actions:
      any:
        - "[SOUND] namespace:test-sound <volume> <pitch>"

**Comment by LoJoSho** [comment]
This will be added to 2.1.0, https://github.com/HibiscusMC/HMCCosmetics/commit/d9b92d5336d052df28663a569c138971e32221c2
