### ISSUE TITLE
[BUG] Weird inventory bug

### ISSUE THREAD

**Issue by Replaycchi** [HibiscusMC/HMCCosmetics#44]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Hi, i've got this weird bug with HmcRemapped, i've tried to update to 2.0.3 but it remains the same. I'm on a purpur 1.19.2 server with the latest available ProtocolLib build for this version
![bug hmc](https://user-images.githubusercontent.com/85904547/213871911-8dafdb96-47f4-4275-87ea-72012b05ad83.gif)

### Steps to reproduce

Just navigate with items in your inventory and it disappear 

### Plugin Version

2.0.3

### Server Version

Current: git-Purpur-1835 (MC: 1.19.2)*

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by LoJoSho** [comment]
This has been fixed in 2.1.0; this was happening because we modify the windows packet which patches several other bugs. Appears we forgot to add a line of code that readds that portion of the packet back in.
