### ISSUE TITLE
[FEATURE] Re-implement "locked-lore" in menus

### ISSUE THREAD

**Issue by Replaycchi** [HibiscusMC/HMCCosmetics#45]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add the "locked-lore" config in menus like in old HMCCosmetics

**Comment by LoJoSho** [comment]
This has the aim of being in 2.1.0, but is not finished. This would include adding lore processing from items to GUI item types.

**Comment by LoJoSho** [comment]
This has been added in 2.1.0 https://github.com/HibiscusMC/HMCCosmetics/commit/53163feb6095849c8521c02e0bbcaa1873be7af8
