### ISSUE TITLE
[FEATURE] Filter option in cosmetic menu.

### ISSUE THREAD

**Issue by mkhansen981017** [HibiscusMC/HMCCosmetics#48]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

A feature for filtering cosmetic items on the server. Filters could be the same as with the HMCWraps plugin:
Filter 1: "Owned" <- this would show all the cosmetics that the player owns
Filter 2: "all" <- this would show all the cosmetic items available on the server

**Comment by LoJoSho** [comment]
Could be similar to the special guis setup with HMCColors; will have to look into this a bit more.
