### ISSUE TITLE
[BUG] ItemsAdder Integration causes progressively worse HMCCosmetics reload loop

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#49]
### I have checked...

- [x] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Originally reported by Mkhansen981017#3753 via the HMCCosmetics Support Channel

When using the HMCCosmetics ItemsAdder integration, every time you reload ItemsAdder it progressively makes HMCCosmetics reload more and more times in a loop. This can cause thousands of lines of reload messages from HMCCosmetics, which is definitely not ideal. 

### Steps to reproduce

1. Install HMCCosmetics + ItemsAdder on your server
2. Run the `/iareload` command, and look at the console output. Continue running the `/iareload` command and notice how the plugin will start to reload more times on each reload.

### Plugin Version

2.1.0

### ModelEngine Version

n/a

### Server Version

This server is running Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd)
You are 169 version(s) behind

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by LoJoSho** [comment]
Fixed https://github.com/HibiscusMC/HMCCosmetics/compare/b96ae68f2417...c52718da585d
