### ISSUE TITLE
[BUG] Eco Window Item Packet visually shows item in old slot with HMCC

### ISSUE THREAD

**Issue by MrApocalyptic** [HibiscusMC/HMCCosmetics#50]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

https://user-images.githubusercontent.com/47505341/216240504-cca49905-9332-46fe-8ea8-8681a23b01eb.mp4

Essentially moving the item around in the inventory becomes a bit buggy, caused by eco the lib for ecoenchants plugin

### Steps to reproduce

Download & install Eco & HMCCosmetics 
https://github.com/Auxilor/eco/releases

### Plugin Version

![image](https://user-images.githubusercontent.com/47505341/216240287-14df0c7c-da2a-4e91-b917-bd4e2b60114e.png)

### ModelEngine Version

![image](https://user-images.githubusercontent.com/47505341/216240251-63983a1e-bf94-45a0-ac85-6dff1099c635.png)

### Server Version

![image](https://user-images.githubusercontent.com/47505341/216240209-899bb722-fc81-4be8-8c02-fb20c3730aa9.png)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by LoJoSho** [comment]
Relevant classes:
https://github.com/Auxilor/eco/blob/master/eco-api/src/main/java/com/willfp/eco/core/display/DisplayModule.java
https://github.com/Auxilor/eco/blob/master/eco-core/core-plugin/src/main/kotlin/com/willfp/eco/internal/spigot/display/PacketWindowItems.kt

**Comment by LoJoSho** [comment]
Eco has completely reworked their packet handler, could you try this again and see if you experience the same issue?

**Comment by MrApocalyptic** [comment]
Yeah it still happens

**Comment by LoJoSho** [comment]
This is something we have tried replicating multiple times with no luck. @lucian929 has eco loaded on the server with HMCC and has had no problems with it. 

It could be any number of issues from the client processing clients differently to whatever else there could be. It's really hard to tell. Either way, this issue will just sit idle with no fix until more information could be found about how to replicate and fix this, hence why I am closing this issue.
