### ISSUE TITLE
[FEATURE] Dyeable 

### ISSUE THREAD

**Issue by MrApocalyptic** [HibiscusMC/HMCCosmetics#51]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Was wondering if we could get dyeable support in the cosmetic apply command, something like /cosmetic apply balloon #FFFFFF

**Comment by LoJoSho** [comment]
This has been added and will be included in a future version, `/cosmetic apply balloon playerName #FFFFFF` https://github.com/HibiscusMC/HMCCosmetics/commit/99bc0a0756c8677444d9b6e962fe5371d1d65a97
