### ISSUE TITLE
[FEATURE] toggle on/off

### ISSUE THREAD

**Issue by Superola86** [HibiscusMC/HMCCosmetics#52]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Make a fuction so we can add a toggle on/off button in the menu.

It changes depeending on if the player is showing or hiding the cosmetics.

**Comment by LoJoSho** [comment]
This has already been added. https://github.com/HibiscusMC/HMCCosmetics/blob/remapped/common/src/main/java/com/hibiscusmc/hmccosmetics/gui/action/actions/ActionCosmeticToggle.java
