### ISSUE TITLE
[FEATURE] instant menu

### ISSUE THREAD

**Issue by maximina16** [HibiscusMC/HMCCosmetics#62]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

when the player open the wardrobe, player should have to left-click. Add an option to player get the menu when he clicked it

**Comment by LoJoSho** [comment]
This already exists, unless you mean something else. When a player clicks while in the wardrobe, it will open the default menu.
