### ISSUE TITLE
[FEATURE] /cosmetic setlocation playerlocation

### ISSUE THREAD

**Issue by maximina16** [HibiscusMC/HMCCosmetics#63]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

The player only see himself when he is near to wardrobe location, some owners (like me) wants to put the (spinning) player to another locations like custom buildings.

**Comment by maximina16** [comment]
fixed with other ways

**Comment by LoJoSho** [comment]
This has to do with the fact we need to summon entities via packets. If player isn't in the area, entity doesn't spawn in, which breaks the wardrobe.
