### ISSUE TITLE
[FEATURE] profile add-on

### ISSUE THREAD

**Issue by magicelk235** [HibiscusMC/HMCCosmetics#64]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

add a profile add-on for HMCcosmetics
That show the cosmetics that you wear 

### Config Changes

HMCcosmetics:
  profile: enable/disable
  
PROFILE FOLDER:
config - permission
menus - edit the items/glyphs 
data - the player data of players

**Comment by LoJoSho** [comment]
This is something that could be considered, although, there are other plugins that already do this.

**Comment by magicelk235** [comment]
Can you give me the names of the other plugins

**Comment by LoJoSho** [comment]
https://www.spigotmc.org/resources/playerprofile.103067/

https://www.spigotmc.org/resources/player-profiles-1-8-1-18-1-custom-model-data-unlimited-guis-highly-customizable.75394/

https://www.spigotmc.org/resources/player-profiles-1-8-1-16-unlimited-guis-placeholderapi-worldguard-support-much-more.77875/

**Comment by magicelk235** [comment]
Are all of the plugins supporting HMCC?

**Comment by LoJoSho** [comment]
No idea, but those are the ones that have been recommended to me over the years.

**Comment by magicelk235** [comment]
One more question
%hmccosmetics_current_<type>_<data>%
this placeholder shows actual items or names?

**Comment by LoJoSho** [comment]
`%hmccosmetics_current_<type>%` returns the cosmetic id.

**Comment by LoJoSho** [comment]
This is not something that I feel will fit into the main plugin. Creating a separate addon would be most advisable if you want such a feature.
