### ISSUE TITLE
[FEATURE] Get multiple Emotes in a file

### ISSUE THREAD

**Issue by Bakayarouz** [HibiscusMC/HMCCosmetics#66]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Would be nice and convenient if the emotes can be done in one single block bench file, that would helps alot in term of... managing emotes and not having to open 500 different blockbench files.

~~Instead of showing a paintbrush in the dye menu, why not just show what the item would look like in that area instead? would be nice as a togglable option.~~

**Comment by LoJoSho** [comment]
For the first one, that would be possible. We will most likely need to redo parts of how emotes are handled to PlayerAnimator (the id), that part was a bit rushed on my part. 

For item in the menu, that would be something for @Boy0000 as he works on HMCColor and there isn't a method to change the actual item as far I can recall. I could be wrong, as I only touched HMCColor briefly before it was added by Boy.

**Comment by Boy0000** [comment]
You can change the cmd and base material. It needs to be leather horse armor, map or potion though cuz colors

**Comment by Bakayarouz** [comment]
> You can change the cmd and base material. It needs to be leather horse armor, map or potion though cuz colors

What i meant was instead of using a custom pre-defined item, why can't it just be the item that is being dyed instead in the colors pickers.

**Comment by Boy0000** [comment]
> What i meant was instead of using a custom pre-defined item, why can't it just be the item that is being dyed instead in the colors pickers.

because the item thats being colored is shown colored in the output?
The reason being is that there are 9 main colors and also subcolors
It would be confusing if it was the item to be dyed

Not planning on changing it to be that sorry
