### ISSUE TITLE
[BUG] Conflict with BattlePass when trying to equip Wings

### ISSUE THREAD

**Issue by RenardFarceur** [HibiscusMC/HMCCosmetics#73]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When I click on my wings to equip my wings cosmetic, I have this error : http://pastebin.fr/116073

### Steps to reproduce

I've download Variety Wings on MC model and convert it on news HMC version :
VSWINGS11:
  slot: BACKPACK
  permission: "hmccosmetics.VSWINGS11"
  item:
    material: IRON_INGOT
    model-data: 11
    name: "Bone Wings"
    amount: 1
    
    For exemple for a wing
 
And when I try to equip on /cosmetic it return the error
    

### Plugin Version

[14:15:51 INFO]: HMCCosmetics version 2.2.3
[14:15:51 INFO]: Author: LoJoSho

### ModelEngine Version

[14:16:04 INFO]: ModelEngine version R3.1.5
[14:16:04 INFO]: Author: Ticxo

### Server Version

[14:16:11 INFO]: This server is running Paper version git-Paper-425 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: ad3e1bc)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by LoJoSho** [comment]
I could be wrong since I don't have access to the BattlePass source code to check myself, but this is a BattlePass issue, not an HMCCosmetics issue. If it is HMCCosmetics, then the BattlePass developer will need to give some information on what they are doing so that we can fix the problem on our end.
