### ISSUE TITLE
`CosmeticUser.getCosmetics()` return type

### ISSUE THREAD

**Issue by Craftinators** [HibiscusMC/HMCCosmetics#80]
**Note:** *As of writing this issue, the method name is `CosmeticUser.getCosmetic()`. I have opened a PR to change this naming to `CosmeticUser.getCosmetics()` and will be referring to the method as the latter.*

Currently, `CosmeticUser.getCosmetics()` returns a mutable `Collection<Cosmetic>`. However, I feel that an `ImmutableCollection<Cosmetic>` return type would be better instead.

Returning an `ImmutableCollection<Cosmetic>` has several advantages over a mutable `Collection<Cosmetic>` one. 

```java
// Old
public Collection<Cosmetic> getCosmetics() {
    return playerCosmetics.values();
}

// New
public ImmutableCollection<Cosmetic> getCosmetics() {
    // Immutable casting 
}
```

Firstly, it ensures that the collection cannot be accidentally modified by other parts of the code, which can lead to unexpected behavior and bugs. With an immutable collection, the state of the collection remains constant, making it easier to reason about and debug.

Secondly, returning an `ImmutableCollection<Cosmetic>` also communicates the intent of the method more clearly. Since `CosmeticUser.getCosmetics()` is only used to retrieve the cosmetics of a user, there is no need for the collection to be mutable. An immutable collection makes it clear that the collection should not be modified and reinforces the intent of the method.

Just to clarify, what’s returned from `HashMap.values()` is a copy of a `Collection`. Modifying the returned `Collection<Cosmetic>` won’t change the `HashMap` in `CosmeticUser` at all, so making it an `ImmutableCollection<Cosmetic>` just makes more sense. If a developer wishes to change the contents of the `HashMap`, then specific methods that make controlled changes should be in place instead. 

*Also this isn't a real benefit for now, nor may it ever be but immutability promotes thread-safety. If the `CosmeticUser.getCosmetics()` method is accessed by multiple threads simultaneously, a mutable collection can result in race conditions and other concurrency issues. An immutable collection eliminates this risk, ensuring that the state of the collection remains consistent regardless of concurrent access.*

**Comment by LoJoSho** [comment]
I would agree with this, plugins should be cloning the collection to have their own copy, but I know that may not be clear right now for plugin developers and they may attempt to make changes in ways that could hurt HMCC on their servers.

**Comment by Craftinators** [comment]
@LoJoSho Good point, but making `CosmeticUser.getCosmetics()` return an `ImmutableCollection<Cosmetic>` wouldn't introduce any breaking changes unless someone is modifying the returned clone. We could solve this by listing `CosmeticUser.getCosmetics()` as deprecated and making a new method, *for example `CosmeticUser.getUserCosmetics()`*, that returns `ImmutableCollection<Cosmetic>`
