### ISSUE TITLE
Riptide enchantment and backpack cosmetics

### ISSUE THREAD

**Issue by snnxx** [HibiscusMC/HMCCosmetics#84]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When trying to throw a trident with a riptide enchantment using BACKPACK cosmetics, the character gets stuck in an invisible armor stand and remains in place

### Steps to reproduce

Just usе any BACKPACK cosmetics and throw a trident with riptide enchantment being in the water looking in any direction 

### Plugin Version

HMCCosmetics version 2.2.5

### Server Version

Paper version git-Paper-245 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b743144)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by LoJoSho** [comment]
Confirmed in 2.2.5. 

The backpack should have no collision, so I am unsure *why* it's getting stuck on it. It also appears that the client is the one who calculates the riptide action, not the server, which adds another layer to this problem. 

I have added the riptide spin attack as a reason to despawn the backpack, but that still doesn't fix the issue at all. Will look into getting more input on this.
