### ISSUE TITLE
[FEATURE] Add an option config to disable WGListener

### ISSUE THREAD

**Issue by WarnDa** [HibiscusMC/HMCCosmetics#87]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

For server owner that don't use the worldguard hook, an option config to disable it would be cool as it's taking 90% of the plugin ressources.
![image](https://user-images.githubusercontent.com/31826333/229302103-91f2fce9-7092-4c58-b5e1-efaa1a615bf9.png)

### Config Changes

player_move_check: false/true

**Comment by LoJoSho** [comment]
I can look into this, but it isn't using that much in terms of resources already, so it's a low priority for me.
