### ISSUE TITLE
[BUG] Can't reload the plugin

### ISSUE THREAD

**Issue by WarnDa** [HibiscusMC/HMCCosmetics#88]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

On /hmc reload the plugin gives an error
https://pastebin.com/UGbFJn0a
Saw another error (may be related) : https://pastebin.com/Dy0AU3W5

### Steps to reproduce

do /hmc reload

### Plugin Version

HMCCosmetics version 2.2.6-DEV
PlaceholderAPI version 2.11.3

### Server Version

 Pufferfish+ version git-PufferfishPlus-44 (1.19.3)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by LoJoSho** [comment]
Need to undo changes in https://github.com/HibiscusMC/HMCCosmetics/commit/3f8f84735fd5532d78ab9a86178c26b779568919 as that is what's causing the issues.
