### ISSUE TITLE
[FEATURE] Automatic and customizable GUI

### ISSUE THREAD

**Issue by mkhansen981017** [HibiscusMC/HMCCosmetics#91]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

A feature that would have the plugin automatically create a GUI with all cosmetics installed to the plugin would be nice.
That way server owners would not have to update the config files every time new cosmetics are added. The ability to specify which gui slots any cosmetic can be shown in would also aid in custom gui setups which some  people might want to have through Unicode symbols in the gui title.

### Config Changes

Valid_gui_slots: 'x,x,x,x' 
Menu_title: " "
Automatic_gui_creation: true/false
  - autodetect_installed_cosmetics: true/false

**Comment by LoJoSho** [comment]
Low priority as this seems like something that goes against the current menu system. Servers that have dozens to hundreds of cosmetics have worked fine with the current system, and not all cosmetics need to have an item configured for them.

**Comment by LoJoSho** [comment]
This would be something better suited for a third party plugin.
