### ISSUE TITLE
[BUG] Helmet slot visible with emotes

### ISSUE THREAD

**Issue by Bakayarouz** [HibiscusMC/HMCCosmetics#97]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

As simple as it gets, emote will show player whatever equipped thing they have on helmet
![image](https://user-images.githubusercontent.com/56614842/233819222-105e47d7-e09d-4631-9b77-8884cb8b3d48.png)

### Steps to reproduce

just emote aye potato

### Plugin Version

Latest yes.

### ModelEngine Version

Nu

### Server Version

1.19.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by LoJoSho** [comment]
Unable to replicate, 
![javaw_jTptUZ1hLx](https://user-images.githubusercontent.com/37521985/233850524-869b7a5d-6a0b-481d-9615-c9e9f61e3dbd.gif)

Version 1.19.2 (Paper-307)

**Comment by Bakayarouz** [comment]
Yeah probably its potato because im on creative, seems to be only a creative thing
