### ISSUE TITLE
[FEATURE] Denizen:my_denizen_item Support

### ISSUE THREAD

**Issue by eyelesstenshi1** [HibiscusMC/HMCCosmetics#98]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

All you would need to add Denizen support is

```
ItemTag item = ItemTag.valueof(id, null);
return item == null ? null : item.getItemStack();
```

Mergu from the Denizen team says that if HMC is open to PRs he is able to add Denizen support!

### Config Changes

ItemTag item = ItemTag.valueof(id, null);
return item == null ? null : item.getItemStack();

**Comment by lucian929** [comment]
Hey there, we're glad to accept (and appreciate!) PRs as long as they follow our basic [PR guidelines](https://github.com/HibiscusMC/HMCCosmetics/blob/remapped/.github/PULL_REQUEST_TEMPLATE.md) 🙂
